version: "3"
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: log-data
        target: /var/log
    networks:
      monitoring:
        ipv4_address: 172.19.0.3

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    stdin_open: true
    tty: true
    networks:
      monitoring:
        ipv4_address: 172.19.0.4

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=your_password
    ports:
      - "8000:8000"
      - "8088:8088"
      - "9997:9997"
    volumes:
      - type: volume
        source: splunk-data
        target: /opt/splunk/var
      - type: volume
        source: log-data
        target: /var/log
    networks:
      monitoring:
        ipv4_address: 172.19.0.5

volumes:
  log-data:
  splunk-data:

networks:
  monitoring:
    ipam:
      config:
        - subnet: "172.19.0.0/24"

