version: "3"
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: log-data
        target: /var/log/shared
    networks:
      - monitoring

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    stdin_open: true
    tty: true
    networks:
      - monitoring

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Splunk#11
    ports:
      - "8000:8000"
      - "8088:8088"
      - "9997:9997"
    volumes:
      - type: volume
        source: splunk-data
        target: /opt/splunk/var
      - type: volume
        source: log-data
        target: /var/log/shared
    networks:
      - monitoring

volumes:
  log-data:
  splunk-data:

networks:
  monitoring:
